services:
  - type: web
    name: tiltify-mayham-webhook
    runtime: python
    plan: starter
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn tiltify:app --host 0.0.0.0 --port $PORT